
-- Generated by ORDS REST Data Services 18.1.1.95.1251
-- Schema: OCTB  Date: Mon Jun 11 03:08:13 2018 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'OCTB',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'taskboard',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'tasks',
      p_base_path      => '/tasks/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'tasks',
      p_pattern        => 'allTasks/',
      p_priority       => 0,
      p_etag_type      => 'NONE',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'tasks',
      p_pattern        => 'allTasks/',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select *
from octb_tasks');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'tasks',
      p_pattern        => 'taskboardTasks/:taskboardId',
      p_priority       => 0,
      p_etag_type      => 'NONE',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'tasks',
      p_pattern        => 'taskboardTasks/:taskboardId',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select *
from octb_tasks
where task_board_id=:taskboardId');

    
    
COMMIT;

END;