CREATE TABLE  "OCTB_TASK_BOARD" 
   (	"TASK_BOARD_ID" NUMBER , 
	"LABEL" VARCHAR2(32) NOT NULL ENABLE, 
	"DESCR" VARCHAR2(4000),
    "AUTHOR_ID" NUMBER,
	 CONSTRAINT "OCTB_TASK_BOARD_PK" PRIMARY KEY ("TASK_BOARD_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OCTB_TASK_BOARD_UK" UNIQUE ("LABEL")
  USING INDEX  ENABLE
   )
/

ALTER TABLE  "OCTB_TASK_BOARD" ADD CONSTRAINT "OCTB_TASK_BOARD_AUTHOR_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES  "OCTB_USERS" ("USER_ID") ON DELETE CASCADE ENABLE
/

ALTER TABLE OCTB_TASKS ADD "ASSIGNEE_ID" NUMBER;
ALTER TABLE OCTB_TASKS ADD "AUTHOR_ID" NUMBER;
ALTER TABLE OCTB_TASKS ADD "TASK_BOARD_ID" NUMBER;
/

ALTER TABLE  "OCTB_TASKS" ADD CONSTRAINT "OCTB_TASKS_FK" FOREIGN KEY ("TASK_BOARD_ID")
	  REFERENCES  "OCTB_TASK_BOARD" ("TASK_BOARD_ID") ON DELETE CASCADE ENABLE
/

ALTER TABLE  "OCTB_TASKS" ADD FOREIGN KEY ("ASSIGNEE_ID")
	  REFERENCES  "OCTB_USERS" ("USER_ID") ENABLE
/
ALTER TABLE  "OCTB_TASKS" ADD FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES  "OCTB_USERS" ("USER_ID") ENABLE
/