CREATE TABLE  "OCTB_GROUPS" 
   (	"GROUP_ID" NUMBER, 
	"LABEL" VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT "OCTB_GROUPS_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OCTB_GROUPS_UK1" UNIQUE ("LABEL")
  USING INDEX  ENABLE
   )
/

CREATE TABLE  "OCTB_USERS" 
   (	"USER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(25), 
	"LAST_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER, 
	"IS_ACTIVE" NUMBER(1,0), 
	"USER_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	 CONSTRAINT "OCTB_USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OCTB_USERS_CON" UNIQUE ("USER_NAME")
  USING INDEX  ENABLE
   )
/