CREATE TABLE  "OCTB_TASKS" 
   (	"TASK_ID" NUMBER, 
	"LABEL" VARCHAR2(64) NOT NULL ENABLE, 
	"DESCR" VARCHAR2(4000), 
	"STATUS_ID" NUMBER NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE" DATE NOT NULL ENABLE, 
	"DUE_DATE" DATE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"COST_IN_HOURS" NUMBER, 
	 CONSTRAINT "OCTB_TASKS_PK" PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE
   )
/

ALTER TABLE  "OCTB_TASKS" ADD CONSTRAINT "OCTB_TASKS_FK3" FOREIGN KEY ("STATUS_ID")
	  REFERENCES  "OCTB_STATUS" ("STATUS_ID") ENABLE
/

ALTER TABLE  "OCTB_TASKS" ADD CONSTRAINT "OCTB_TASKS_FK2" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES  "OCTB_CATEGORIES" ("CATEGORY_ID") ENABLE
/