create sequence OCTB_CATEGORIES_SEQ;
create sequence OCTB_STATUS_SEQ;
/

CREATE OR REPLACE TRIGGER OCTB_CATEGORIES_TRG_I 
BEFORE INSERT ON OCTB_CATEGORIES 
FOR EACH ROW
BEGIN
  :NEW.CATEGORY_ID:=OCTB_CATEGORIES_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER OCTB_STATUS_TRG_I 
BEFORE INSERT ON OCTB_STATUS
FOR EACH ROW
BEGIN
  :NEW.STATUS_ID:=OCTB_STATUS_SEQ.NEXTVAL;
END;
/