CREATE TABLE  "OCTB_CATEGORIES" 
   (	"CATEGORY_ID" NUMBER , 
	"LABEL" VARCHAR2(32) NOT NULL ENABLE, 
	"SORT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "OCTB_CATEGORIES_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OCTB_CATEGORIES_UK1" UNIQUE ("LABEL")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "OCTB_STATUS" 
   (	"STATUS_ID" NUMBER , 
	"LABEL" VARCHAR2(32) NOT NULL ENABLE,  
	"SORT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "OCTB_STATUS_PK" PRIMARY KEY ("STATUS_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "OCTB_STATUS_UK" UNIQUE ("LABEL")
  USING INDEX  ENABLE
   )
/

ALTER TABLE  "OCTB_CATEGORIES" ADD CONSTRAINT "OCTB_CATEGORIES_FK2" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES  "OCTB_CATEGORIES" ("CATEGORY_ID") ENABLE
/